# Generated by Django 2.2.3 on 2019-07-09 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('account', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.Permission')),
            ],
        ),
    ]
